### PR TITLE
option to disable default mappings

### PR DESCRIPTION
**Pull request by flipcoder**

### CODE REVIEW

**Comment by tpope** [comment]
Which one is irking you? I'll add an option before release but until then I want to hear complaints.

**Comment by flipcoder** [comment]
No issue with the mapping choices, they just happen to clobber existing custom mappings that I was using previously.  Whenever that happens I look for a way to override it in the plugin.  The other plugins that I have to do this with have a similar naming and check for overriding defaults.

**Comment by tpope** [comment]
I wanna hear about custom mappings this conflicts with because if there are common ones I'll avoid one.

**Comment by flipcoder** [comment]
For me it was apostrophe (') which I have mapped as a fast scroll motion, so when the plugin defaults there is a delay.  I used my own custom macro setup before vim (it was very similar vim but it had operators on left hand and motions on the right hand, so the keys were different).  When i transitioned to vim I remapped those so they wouldn't make much sense for anyone else.

**Comment by tpope** [comment]
You might appreciate `<nowait>`.

**Pull request closed without merging**
