### PR TITLE
Add :Make support to X11 handler

### PR DESCRIPTION
**Pull request by zorab47**
Allow X11 handler to execute both :Make and :Start commands.

See #127 for initial discussion.

### CODE REVIEW

**Comment by tpope** [comment]
`:Make` should never grab focus. You'll need to squash in my previous patch for starters.

**Comment by zorab47** [comment]
I rebased my branch to include your commit. I can squash them together if you prefer.

Are there any other changes needed/

**Comment by tpope** [comment]
Yes, please squash. After that it looks good to go, and I will personally test it.

**Comment by zorab47** [comment]
I squashed them together. Thanks!

**Comment by tpope** [comment]
Huh, this isn't consistently working for me because my terminal takes more than 100ms to launch sometimes. How about you?

**Comment by tpope** [comment]
Found a solution and squashed it into your commit.

**Comment by tpope** [comment]
BTW I am wondering if it would make more sense to minimize the window, except in the `:Start` case. Using a tiling window manager, I am finding the rearrange super disrupting.

**Comment by zorab47** [comment]
With a tiling window manager that would be very disruptive. `wmctrl` doesn't offer a method of minimizing windows, at least nothing stood out. Some terminals may have a CLI switch for starting minimized, although `gnome-terminal` is missing the option.

[Searching more in depth][1] I found that a newer version of `wmctrl` does provide the iconify option, but it isn't currently available via apt on Ubuntu 14.04. The `xdotool` might be another option.

[1]:http://askubuntu.com/questions/488356/how-can-i-start-a-script-in-a-minimised-gnome-terminal

**Comment by tpope** [comment]
Is there a difference between iconification and what `-b add,hidden` does?

**Comment by zorab47** [comment]
Using `-b add,hidden` didn't hide or minimize the window when I tried it in Xfce.

**Comment by tpope** [comment]
I guess no harm in adding it then :). Will investigate further in the
future.

**Pull request closed without merging**
