### PR TITLE
Add capability to configure the tmux pane height

### PR DESCRIPTION
**Pull request by gabriel128**
Enable the chance of using g:dispatch_pane_size to configure the height of the pane opened in tmux
- Add extra conditional to tmux.vim file

### CODE REVIEW

**Comment by phongnh** [comment]
+1

**Comment by zabolotnov87** [comment]
+1

**Comment by tpope** [comment]
Okay I guess I'll capitulate, but make it `get(g:, 'dispatch_quickfix_height', 10)`, and have it affect the quickfix window too.

**Comment by Smeagol07** [comment]
+1
@tpope 
Can the quickfix use a separate setting? Like dispatch_quickfix_height and dispatch_tmux_height?
I would like to combine this option with ack.vim plugin and it would be nice to have small tmux panel (as one don't need to see a progress) but normal quickfix (as the final result is important).
I will make a pull request if that's ok.

**Comment by Smeagol07** [comment]
+1
@tpope 
Can the quckfix have diferent option than tmux panel? Like `dispatch_quickfix_height` and `dispatch_tmux_height`?
I would like to use it in `ack.vim` plugin and it would be nice to have small panel when a search is in progress and nice quickfix at the end.
If so I will make a pull request.

**Comment by gabriel128** [comment]
I'm going to close this PR since I moved to emacs, and I'd rather not write any more vimscript in my whole life :wave:

**Pull request closed without merging**
