### PR TITLE
allow custom message handler

### PR DESCRIPTION
**Pull request by p00f**
This is #320 but from a separate branch

### CODE REVIEW

**Comment by p00f** [comment]
Is there interest in this/should I close it?

**Comment by tpope** [comment]
I would rather see this done with a `QuickFixCmdPost` autocommand if at all possible. I haven't investigated what it would take to achieve this.

**Comment by p00f** [comment]
I don't understand the `doautocmd` in autoload/dispatch.vim, the help for `doautocmd` says

`:do[autocmd] [<nomodeline>] [group] {event} [fname]` which means `dispatch-make-complete` is a file but `dispatch-make-complete` is only used in the `silent doautocmd Event dispatch-make-complete` position

**Comment by p00f** [comment]
Closed by mistake

**Comment by tpope** [comment]
`[fname]` isn't always a file.

**Comment by p00f** [comment]
Do you mean calling `s:doautocmd('QuickFixCmdPost dispatch-echo')` from `s:echo_truncated` and adding the call to the handler in https://github.com/tpope/vim-dispatch/blob/527f200fb86c18d1cc7dc702d13f8818dced04ac/plugin/dispatch.vim#L100 ?

**Comment by tpope** [comment]
More or less yes, but I think it should be higher level than that, maybe something like `dispatch-make-done`, with both `Pre` and `Post` versions.

**Pull request closed without merging**
